### ISSUE TITLE
Add issue bot

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1765]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
Add issue bot

### Feature / Enhancement Description
Add issue bot

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### 3rd Party References
n/a
