### ISSUE TITLE
Docker images are not updated on docker hub anymore

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-dashboard#1782]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Docker Hub made some [changes](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/) around a month ago that stopped automatic builds for free accounts. So no new commits to the dashboard or releases are being pushed.

### Steps to reproduce
- Merge a commit or make a release
- Go to https://hub.docker.com/r/parseplatform/parse-dashboard and see that the last image was pushed over a month ago.

### Actual Outcome
Old image of dashboard

### Expected Outcome
Latest image when commits are made to the master branch and released images with respect to the tag

### Environment

Dashboard
- Parse Dashboard version: 2.2.0
- Browser (Safari, Chrome, Firefox, Edge, etc.): Safari
- Browser version: lastest

Server
- Parse Server version: latest
- Operating system: Linux
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Docker

Database
- System (MongoDB or Postgres): MongoDB
- Database version: latest
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-dashboard/commit/d207347e4e79c26255ba9ffb460ca3df8348f9fd
