### ISSUE TITLE
Current version of sass preventing ability to run on node lts

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-dashboard#1793]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The docker image the dashboard is built on isn't lts. The reason for this is the sass is too outdated and can't run on node lts

### Steps to reproduce

Try to build the dashboard on node lts

### Actual Outcome

Build will fail

### Expected Outcome

Dashboard should always build on lts.

### Environment

Dashboard
- Parse Dashboard version: `master`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `N/A`

Server
- Parse Server version: `4.10.3`
- Operating system: `Docker linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `13`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

### Logs

https://github.com/netreconlab/parse-dashboard/runs/3545759058?check_suite_focus=true#step:7:378
