### ISSUE TITLE
Push recent tags to docker hub

### ISSUE THREAD

**Issue by Klaitos** [parse-community/parse-dashboard#1794]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
As the docker CI was not fired 2 last years, please upload recents tags to docker hubs (2.0.5 is the last one on the hub)

### Steps to reproduce
https://hub.docker.com/r/parseplatform/parse-dashboard/tags?page=1&ordering=last_updated

### Actual Outcome
Last stable tag available is 2.0.5

### Expected Outcome
tag 2.2, 2.1 are available

### Environment

Dashboard
- Parse Dashboard version: `2.0.5`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `FILL_THIS_OUT`

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

**Comment by mtrezza** [comment]
Old versions cannot easily be published as docker images as they had a dev-dependency on Parse Server `master` branch, since removed in https://github.com/parse-community/parse-dashboard/pull/1796. Since these old Parse Dashboard images require a lower Node version (usually around 8), but Parse Server `master` today requires at least Node 12, they have build issues. Possibly also related to the docker base node image used in these builds.

Closing as won't fix.
