### ISSUE TITLE
[Discuss] how about creating development roadmap?

### ISSUE THREAD

**Issue by Beingbook** [parse-community/parse-dashboard#467]
I could see being implemented features in `parse-dashboard`. If there's a roadmap or feature list, I think `ParsePlatform` users probably do more.

like this (actually the tasks should be more clear and measurable):
### has name and in code but not implemented
- [ ] schema-overview
- [ ] getting-started page
- [ ] unreached relation or pointers find page (garbage collector)
- [ ] file upload configuration for each fields (actually `parse-server`)
### project maintainabilities
- [ ] upgrade babel 6 from babel 5 (with removing decorators)
- [ ] apply `Browser` component flow
- [ ] apply `eslint`

I had no opportunity to use `Parse` service. But I guess more features was implemented in the service before `ParsePlatform` open source.
